version: "3.5"
services: 
  example-golang-api-service:
    container_name: "example-golang-api"
    image: "ruyjfs/go"
    build: docker/.
    working_dir: /app
    volumes:
      - .:/app
    env_file: ./docker/docker.env
    entrypoint: ["sh", "./docker/entrypoint.sh"]
    command: sh -c 'gin --port=8080'
    ports:
      - "8085:8080"
    restart: always
    tty: true
    links:
      - example-golang-db-service
    depends_on:
      - example-golang-db-service
  example-golang-db-service:
    container_name: example-golang-db
    image: postgres:alpine
    env_file: ./docker/docker.env
    volumes:
      - ./docker/database/postgres/data:/var/lib/postgresql/data
      - ./docker/database/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    tty: true
    restart: always
    healthcheck:
      #IMPORTANT! change this if you have changed a local.env
      test: ["CMD-SHELL", "pg_isready -U example-golang-usr -d example-golang-db"]
      interval: 10s
      timeout: 5s
      retries: 5
  example-golang-adminer-service:
    container_name: example-golang-adminer
    image: adminer
    restart: always
    ports:
      - 8086:8080
    env_file: ./docker/docker.env
    links:
      - example-golang-db-service
    depends_on:
      - example-golang-db-service